import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider"
import Menubar from "@/components/shared/Menubar";
import {getCurrentUser} from '@/infraestructure/features/auth/session'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getCurrentUser()

  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <div
        className="flex flex-col min-h-screen font-sans text-base bg-background text-foreground dark:bg-background-dark dark:text-foreground-dark">
        {user && (<Menubar/>)}

        {children}

      </div>
    </ThemeProvider>
    </body>
    </html>
  );
}
